### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by hoshsadiq** [elgatito/elementum#15]
Hello, I'm trying to setup a dev environment, got a whole lot of dependencies missing (c dependencies that is). Do you have a list of all the dependencies required to build?

**Comment by elgatito** [comment]
@hoshsadiq build process is the same as for Quasar. 
So if you want to build locally (not in Docker image), then you need libtorrent-go package, which needs libtorrent installed locally.

You can look here: https://github.com/scakemyer/libtorrent-go
Or here: https://github.com/elementumorg/libtorrent-go

**Comment by hoshsadiq** [comment]
> So if you want to build locally (not in Docker image)

I guess it can be in docker image, but I'm not aware of any way of getting IntelliJ to run go code inside docker.

Will have a look at both of those when I get home and will report back!

**Comment by hoshsadiq** [comment]
Couldn't really get any of it to work lol. Even within docker. Can I ask what your current work flow is for development?

**Comment by elgatito** [comment]
What exactly does not work for you?
you need libtorrent-go module installed + libtorrent static library.

**Comment by hoshsadiq** [comment]
I'm unable to build.

```
~/go/src/github.com/ElementumOrg/libtorrent-go # make linux-x64
make build TARGET_OS=linux TARGET_ARCH=x64
make[1]: Entering directory '/root/go/src/github.com/ElementumOrg/libtorrent-go'
docker run --rm -v /root/go:/go -e GOPATH=/go -v /root/go/src/github.com/ElementumOrg/libtorrent-go:/go/src/github.com/elgatito/elementum -w /go/src/github.com/elgatito/elementum quasarhq/libtorrent-go:linux-x64 make dist TARGET_OS=linux TARGET_ARCH=x64 GIT_VERSION=v0.1.24-1-g066550c
LDFLAGS='' \
CFLAGS=' -std=c++11' \
CC='x86_64-linux-gnu-cc' CXX='x86_64-linux-gnu-c++' \
GOOS='linux' GOARCH='amd64' GOARM='' \
CGO_ENABLED='1' \
go build -v \
	-gcflags '' \
	-ldflags '-linkmode=external -extld=x86_64-linux-gnu-cc -extldflags "-lm" -s -w -X github.com/elgatito/elementum/util.Version=v0.1.24-1-g066550c' \
	-o 'build/linux_x64/elementum' \
	
api/torrents.go:15:2: import "github.com/ElementumOrg/libtorrent-go" is a program, not an importable package
import cycle not allowed
package github.com/elgatito/elementum
	imports github.com/elgatito/elementum/api
	imports github.com/ElementumOrg/libtorrent-go
	imports github.com/elgatito/elementum/api
make: *** [build/linux_x64/elementum] Error 1
Makefile:123: recipe for target 'build/linux_x64/elementum' failed
make[1]: *** [Makefile:165: build] Error 2
make[1]: Leaving directory '/root/go/src/github.com/ElementumOrg/libtorrent-go'
make: *** [Makefile:111: linux-x64] Error 2
```

Also, I wonder, what editor do you use? Do you make edits and compile then run manually or do you let your editor handle it?

**Comment by elgatito** [comment]
On jenkins I do this:
```
export GOPATH=$HOME/go

# For github.com/elgatito/elementum
git checkout master
cd ~/go/src/github.com/elgatito/elementum
go get -u ./...
make linux-x64
```

Docker is only using dockerized compiler and libraries, sources are used from $GOPATH directory, so make sure you place directories properly.

**Comment by elgatito** [comment]
There is a `test_build.sh` script which compiles locally.

**Comment by hoshsadiq** [comment]
So do you use the build from `test_build.sh` to then launch kodi so you can test your changes?

**Comment by elgatito** [comment]
Yes. Or you can run with a docker, result will be the same - binary file in `build/` directory.

**Comment by hoshsadiq** [comment]
cool.

Stuck on this now, can't find anything else that could possibly get `libtorrent-rasterbar`.

```
~/go/src/github.com/elgatito/elementum # go get ./...
# pkg-config --cflags --static -- libtorrent-rasterbar openssl
Package libtorrent-rasterbar was not found in the pkg-config search path.
Perhaps you should add the directory containing `libtorrent-rasterbar.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libtorrent-rasterbar', required by 'virtual:world', not found
pkg-config: exit status 1
~/go/src/github.com/elgatito/elementum # apk list --installed | grep -i torrent
libtorrent-dev-0.13.7-r1 x86_64 {libtorrent} (GPL) [installed]
libtorrent-0.13.7-r1 x86_64 {libtorrent} (GPL) [installed]
```

**Comment by elgatito** [comment]
As I've said before, you need to compile libtorrent library. Not just install some package. 
Because you need static library, with specific features and compiled with the same compiler.

You can look here:
https://github.com/ElementumOrg/libtorrent-go/blob/master/linux-x64/Dockerfile

You will need boost -> openssl -> swig -> libtorrent compilation.

**Comment by elgatito** [comment]
Latest version has dependency only on libtorrent-go docker image. cross-compiler images are not used for the moment.

You can just install gcc locally and then look into docker file for your platform (probably linux-x64) and install everything to /usr/local/ or something. Add directories to LD_LIBRARY_PATH and place libtorrent-go directory into $GOPATH/src/github.com/ElementumOrg/libtorrent-go/

**Comment by elgatito** [comment]
With the latest version of `ElementumOrg/libtorrent-go` repository, you can run `make local-env` to have all the dependencies locally. Then set `PKG_CONFIG_PATH` to that directory's `lib` dir. 
And then you will have all the required env for compiling Elementum.
