### ISSUE TITLE
Add-on install failure after compile

### ISSUE THREAD

**Issue by rocknroll** [elgatito/elementum#17]
Hello,

I'have compiled elementum deamon successfully, but kodi just says failed to install from zip file. Something is missing i think. After deamon creation i just downloaded original elementum plugin as zip, extracted it and replaced my compiled deamon and "libc++_shared.so" file inside the folder resources/bin/android_arm and zipped whole folder again. Do i need to make any other configurations?

 I just realized after compile i have only 2 files but original plugin under bin has 3 files :

`ls build/android_arm/`

elementum
libc++_shared.so

but there is no libgnustl_shared.so, maybe this is the case? But i have zipped with the original libgnustl_shared.so included still no success.

**Comment by elgatito** [comment]
@rocknroll you should look into existing Makefiles for Elementum.

If you use old Android NDK - you will have `libgnustl_shared.so` file in your NDK `/lib/` dir.
If you use new NDK - you will have `libc++_shared.so`. 
You should use exactly that shared so file with your binary.

**Comment by rocknroll** [comment]
@elgatito yes i have done exactly like that but still no success. 

To create elementum deamon i have followed the steps you have mentioned :

`https://github.com/elgatito/elementum`

This is `make android-arm` output :

> in ~/go/src/github.com/elgatito/elementum on master*
> $ make android-arm
> /Library/Developer/CommandLineTools/usr/bin/make build TARGET_OS=android TARGET_ARCH=arm
> docker run --rm -v /Users/hex/go:/go -e GOPATH=/go -v /Users/hex/go/src/github.com/elgatito/elementum:/go/src/github.com/elgatito/elementum -w /go/src/github.com/elgatito/elementum libtorrent-go:android-arm make dist TARGET_OS=android TARGET_ARCH=arm GIT_VERSION=v0.1.41-1-ga706988
> LDFLAGS='' \
> CFLAGS=' -std=c++11' \
> CC='/usr/arm-linux-androideabi/bin/arm-linux-androideabi-clang' CXX='/usr/arm-linux-androideabi/bin/arm-linux-androideabi-clang++' \
> GOOS='android' GOARCH='arm' GOARM='7' \
> CGO_ENABLED='1' \
> go build -v \
> 	-gcflags '' \
> 	-ldflags '-linkmode=external -extld=/usr/arm-linux-androideabi/bin/arm-linux-androideabi-clang -extldflags "-pie -lm"  -s -w -X github.com/elgatito/elementum/util.Version=v0.1.41-1-ga706988' \
> 	-o 'build/android_arm/elementum' \
> 
> github.com/bradfitz/iter
> github.com/asdine/storm/codec
> runtime/cgo
> github.com/anacrolix/missinggo/slices
> github.com/huandu/xstrings
> github.com/dustin/go-humanize
> github.com/pkg/errors
> github.com/asdine/storm/codec/json
> github.com/asdine/storm/q
> go.etcd.io/bbolt
> github.com/cespare/xxhash
> github.com/philhofer/fwd
> github.com/pbnjay/memory
> github.com/sanity-io/litter
> github.com/tinylib/msgp/msgp
> golang.org/x/net/html/atom
> golang.org/x/net/html
> net
> github.com/asdine/storm/internal
> github.com/asdine/storm/index
> github.com/asdine/storm
> github.com/andybalholm/cascadia
> gopkg.in/sourcemap.v1/base64vlq
> gopkg.in/sourcemap.v1
> github.com/robertkrimen/otto/file
> github.com/robertkrimen/otto/token
> github.com/robertkrimen/otto/dbg
> github.com/robertkrimen/otto/ast
> github.com/robertkrimen/otto/registry
> golang.org/x/crypto/ed25519
> golang.org/x/net/bpf
> golang.org/x/net/internal/iana
> golang.org/x/sys/unix
> golang.org/x/text/transform
> github.com/robertkrimen/otto/parser
> golang.org/x/text/unicode/bidi
> golang.org/x/text/secure/bidirule
> golang.org/x/text/unicode/norm
> github.com/robertkrimen/otto
> github.com/likexian/gokit/assert
> golang.org/x/net/idna
> github.com/elgatito/elementum/jsonrpc
> github.com/anacrolix/missinggo
> github.com/op/go-logging
> github.com/Diggernaut/goquery
> github.com/elazarl/goproxy
> github.com/anacrolix/missinggo/iter
> github.com/anacrolix/log
> github.com/anacrolix/missinggo/perf
> github.com/anacrolix/sync
> github.com/anacrolix/envpprof
> github.com/anacrolix/tagflag
> github.com/elgatito/elementum/xbmc
> golang.org/x/net/internal/socket
> github.com/likexian/doh-go/dns
> github.com/likexian/gokit/xcache/memory
> github.com/likexian/gokit/xcache
> github.com/likexian/gokit/xfile
> golang.org/x/net/ipv4
> golang.org/x/net/ipv6
> github.com/elgatito/elementum/config
> github.com/likexian/gokit/xstring
> github.com/likexian/gokit/xhash
> github.com/likexian/gokit/xjson
> github.com/likexian/gokit/xrand
> github.com/likexian/gokit/xtime
> github.com/miekg/dns
> github.com/likexian/gokit/xip
> github.com/gin-contrib/sse
> github.com/likexian/gokit/xhttp
> github.com/gin-gonic/gin/internal/json
> github.com/golang/protobuf/proto
> github.com/likexian/doh-go/provider/cloudflare
> github.com/ElementumOrg/cfbypass
> github.com/likexian/doh-go/provider/dnspod
> github.com/likexian/doh-go/provider/google
> github.com/likexian/doh-go/provider/quad9
> github.com/likexian/doh-go
> github.com/ugorji/go/codec
> github.com/go-playground/locales/currency
> github.com/go-playground/locales
> github.com/go-playground/universal-translator
> github.com/leodido/go-urn
> gopkg.in/go-playground/validator.v9
> gopkg.in/yaml.v2
> github.com/mattn/go-isatty
> github.com/golang/snappy
> github.com/glycerine/go-unsnap-stream
> github.com/RoaringBitmap/roaring
> github.com/elgatito/elementum/broadcast
> github.com/boltdb/bolt
> github.com/bogdanovich/dns_resolver
> github.com/elgatito/elementum/proxy
> github.com/elgatito/elementum/diskusage
> github.com/klauspost/compress/flate
> github.com/vmihailenco/msgpack/codes
> github.com/vmihailenco/tagparser/internal
> github.com/vmihailenco/tagparser/internal/parser
> github.com/vmihailenco/tagparser
> github.com/vmihailenco/msgpack
> github.com/klauspost/compress/gzip
> github.com/elgatito/elementum/playcount
> github.com/jmcvetta/napping
> github.com/karrick/godirwalk
> github.com/kolo/xmlrpc
> github.com/fatih/color/vendor/github.com/mattn/go-isatty
> github.com/radovskyb/watcher
> github.com/fatih/color/vendor/github.com/mattn/go-colorable
> github.com/fatih/color
> github.com/shirou/gopsutil/internal/common
> github.com/valyala/bytebufferpool
> github.com/scakemyer/quasar/osdb
> github.com/zeebo/bencode
> github.com/elgatito/elementum/lockfile
> github.com/shirou/gopsutil/mem
> github.com/gin-gonic/gin/render
> github.com/gin-gonic/gin/binding
> github.com/gin-gonic/gin
> github.com/elgatito/elementum/api/repository
> github.com/elgatito/elementum/util
> github.com/elgatito/elementum/repository
> github.com/elgatito/elementum/database
> github.com/elgatito/elementum/cache
> github.com/elgatito/elementum/fanart
> github.com/elgatito/elementum/tvdb
> github.com/elgatito/elementum/tmdb
> github.com/elgatito/elementum/osdb
> github.com/elgatito/elementum/trakt
> github.com/elgatito/elementum/library
> github.com/elgatito/elementum/bittorrent
> github.com/elgatito/elementum/providers
> github.com/elgatito/elementum/scrape
> github.com/elgatito/elementum/api
> # set -x && \
> # go vet -unsafeptr=false .
> chmod -R 777 build/android_arm
> cp /usr/arm-linux-androideabi/sysroot/usr/lib/arm-linux-androideabi/libc++_shared.so build/android_arm
> chmod +rx build/android_arm/libc++_shared.so
> # cp /usr/arm-linux-androideabi/arm-linux-androideabi/lib/libgnustl_shared.so build/android_arm
> # chmod +rx build/android_arm/libgnustl_shared.so
> # Temporary disable strip
> # @find build/android_arm -type f ! -name "*.exe" -exec arm-linux-androideabi-strip {} \;
> shasum -b build/android_arm/elementum | cut -d' ' -f1 >> build/android_arm/elementum

after this i have 2 file "elementum" and "libc++_shared.so" under the build/android_arm

for the next step i have downloaded elementum plugin for android :

https://github.com/elgatito/plugin.video.elementum/releases/download/v0.1.41/plugin.video.elementum-0.1.41.android_arm.zip

extracted it and replaced "elementum" and "libc++_shared.so" with my new compiled files under resources/bin/android_arm and zipped it again.

but kodi (last version) fails to install this zip i think i'm doing something wrong? Or elementum binary that i have created has a problem but i don't see any problem if i look to output, you can check it. If i try official plugin zip file it is success, after file replacement i doesn't work.

**Comment by rocknroll** [comment]
@elgatito I have figured it out! It looks like mac os DS Store and __MACOSX folders are causing the problem inside the zip file. I have zipped without them and it worked like a charm! 👍

`zip -r plugin.zip pluginFolder -x ".*" -x "__MACOSX"`

Thank you for your support and contribution to community.
