### ISSUE TITLE
Elementum for Android deletes torrent file from 'add torrent's menu

### ISSUE THREAD

**Issue by alcuindeverellmoras** [elgatito/elementum#21]
I download and store torrents and play them with Elementum through the 'add torrent' option, selecting the torrent file. However, once I've started the torrent, it is automatically deleted. I want the torrent file to be left alone, how do I do this?

**Comment by elgatito** [comment]
No log - no help.

**Comment by alcuindeverellmoras** [comment]
How do you upload a log?

**Comment by elgatito** [comment]
@alcuindeverellmoras http://elementum.surge.sh/contribute/log/#easy-one

**Comment by alcuindeverellmoras** [comment]
paste.kodi.tv/pakinanuwa

**Comment by alcuindeverellmoras** [comment]
paste.kodi.tv/qayucerugu

**Comment by alcuindeverellmoras** [comment]
Posted debug/bundle and debug/all as I didn't know which one you needed

**Comment by elgatito** [comment]
@alcuindeverellmoras Kodi has only current execution log. You need to reproduce the issue, then make a log file.

**Comment by alcuindeverellmoras** [comment]
What exactly do I do to reproduce the issue? It deletes a torrent file from my device everytime I play it through 'add torrent'. I want it to stop deleting the torrent.

**Comment by elgatito** [comment]
You need to catch a bug and then upload the log.

**Comment by alcuindeverellmoras** [comment]
I don't have a bug exactly. I just want Elementum for Android to stop deleting the torrents that I download, when I play them. I want them to stay in the folder. I want to keep my .torrent files saved.

**Comment by elgatito** [comment]
Ok. You don't want to provide required information. I don't have that bug.

**Comment by alcuindeverellmoras** [comment]
I want your help, I want to know how to stop Elementum for Android from deleting .torrent files. Please help me, it's not a bug and I don't know what settings to change because I've tried so many times and it doesn't help.

**Comment by elgatito** [comment]
@alcuindeverellmoras it is clear what you need to make.
Open Kodi. Make what you did to encounter a "bug". Make log file.

**Comment by alcuindeverellmoras** [comment]
paste.kodi.tv/lujujiwori

**Comment by alcuindeverellmoras** [comment]
paste.kodi.tv/rucetijehe
