### ISSUE TITLE
Не правильно работает выбор стрима для сезона

### ISSUE THREAD

**Issue by Nemiroff** [elgatito/elementum#5]
При выборе из контекстного меню "Выбрать стрим", появляется ошибка Not Found
> 02:36:22 T:4604   DEBUG: XFILE::CPluginDirectory::StartScript - calling plugin Elementum('plugin://plugin.video.elementum/show/60735/season/3/play','7','')
02:36:22 T:4604   DEBUG: XFILE::CPluginDirectory::WaitOnScriptResult - waiting on the Elementum (id=12) plugin...
02:36:22 T:4788   DEBUG: Thread LanguageInvoker start, auto delete: false
02:36:22 T:4788    INFO: initializing python engine.
02:36:22 T:4788   DEBUG: CPythonInvoker(12, C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.elementum\navigation.py): start processing
02:36:22 T:4788   DEBUG: -->Python Interpreter Initialized<--
02:36:22 T:4788   DEBUG: CPythonInvoker(12, C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.elementum\navigation.py): the source file to load is "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.elementum\navigation.py"
02:36:22 T:4788   DEBUG: CPythonInvoker(12, C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.elementum\navigation.py): setting the Python path to C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.elementum;C:\Program Files\Kodi\system\python\DLLs;C:\Program Files\Kodi\system\python\Lib;C:\Program Files\Kodi\python27.zip;C:\Program Files\Kodi\system\python\lib\plat-win;C:\Program Files\Kodi\system\python\lib\lib-tk;C:\Program Files\Kodi;C:\Program Files\Kodi\system\python;C:\Program Files\Kodi\system\python\lib\site-packages
02:36:22 T:4788   DEBUG: CPythonInvoker(12, C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.elementum\navigation.py): entering source directory C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.elementum
02:36:22 T:4788   DEBUG: CPythonInvoker(12, C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.elementum\navigation.py): instantiating addon using automatically obtained id of "plugin.video.elementum" dependent on version 2.24.0 of the xbmc.python api
02:36:22 T:4788   DEBUG: [plugin.video.elementum] Requesting http://localhost:65220/show/60735/season/3/play from ['plugin://plugin.video.elementum/show/60735/season/3/play', '7', '']
02:36:22 T:5040  NOTICE: [plugin.video.elementum] [GIN] 2018/02/22 - 02:36:22 | 404 |            0s |             ::1 | GET      /show/60735/season/3/play
02:36:22 T:4788   ERROR: [plugin.video.elementum] Traceback (most recent call last):
02:36:22 T:4788   ERROR: [plugin.video.elementum]   File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.elementum\resources\site-packages\elementum\navigation.py", line 186, in run
02:36:22 T:4788   ERROR: [plugin.video.elementum]     data = _json(url)
02:36:22 T:4788   ERROR: [plugin.video.elementum]   File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.elementum\resources\site-packages\elementum\navigation.py", line 128, in _json
02:36:22 T:4788   ERROR: [plugin.video.elementum]     with closing(urllib2.urlopen(url)) as response:
02:36:22 T:4788   ERROR: [plugin.video.elementum]   File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 127, in urlopen
02:36:22 T:4788   ERROR: [plugin.video.elementum]     return _opener.open(url, data, timeout)
02:36:22 T:4788   ERROR: [plugin.video.elementum]   File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 410, in open
02:36:22 T:4788   ERROR: [plugin.video.elementum]     response = meth(req, response)
02:36:22 T:4788   ERROR: [plugin.video.elementum]   File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 523, in http_response
02:36:22 T:4788   ERROR: [plugin.video.elementum]     'http', request, response, code, msg, hdrs)
02:36:22 T:4788   ERROR: [plugin.video.elementum]   File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 448, in error
02:36:22 T:4788   ERROR: [plugin.video.elementum]     return self._call_chain(*args)
02:36:22 T:4788   ERROR: [plugin.video.elementum]   File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 382, in _call_chain
02:36:22 T:4788   ERROR: [plugin.video.elementum]     result = func(*args)
02:36:22 T:4788   ERROR: [plugin.video.elementum]   File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 531, in http_error_default
02:36:22 T:4788   ERROR: [plugin.video.elementum]     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
02:36:22 T:4788   ERROR: [plugin.video.elementum] HTTPError: HTTP Error 404: Not Found
02:36:22 T:4788   ERROR: [plugin.video.elementum]
02:36:22 T:4788    INFO: CPythonInvoker(12, C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.elementum\navigation.py): script successfully run

Если в настройках включить опцию "Выбирать стрим автоматически", то показывается список найденых раздач. Автоматический запуск не происходит.
С включенной настройкой автоматически стартуют фильмы и конкретные серии из сезона.
Началось всё с комита 3b46ce0f49bf3da8b56b508d9c78ac40b88191b1

**Comment by elgatito** [comment]
Should be fixed in the next version.

**Comment by elgatito** [comment]
Пробуйте с 0.0.44

**Comment by Nemiroff** [comment]
Работает, но в точности наоборот. С включенной опцией "Автоматический выбор стрима" выводит окно со списком. С отключенной опцией начинает сразу воспроизводить стрим.

**Comment by elgatito** [comment]
В версии 0.0.45 исправится надпись в контекстном меню для сезонов.

**Comment by Nemiroff** [comment]
Но надпись то там одна Выбрать стрим.

**Comment by elgatito** [comment]
> исправится надпись

**Comment by Nemiroff** [comment]
Надпись исправилась, но логика тогда не понятна. Сейчас:
Настройка Elementum `Выбрать стрим автоматически - Включена` - в контекстном меню сезона `Выбрать стрим...`, Показывается окно с раздачами.
Настройка Elementum `Выбрать стрим автоматически - Отключена` - в контекстном меню сезона `Выбрать стрим автоматически`, происходит автовыбор раздачи.

**Comment by Nemiroff** [comment]
Ошибка скорее всего в `func contextPlayOppositeURL(f string, forced bool) string {
	action := "links"
	if !config.Get().ChooseStreamAuto {
		action = "play"
	}
	if forced {
		action = "force" + action
	}

	return fmt.Sprintf(f, action)
}` а конкретнее в `if !`

**Comment by Nemiroff** [comment]
Текущая логика удобна для эпизодов и фильмов, так как по выбору эпизода/фильма происходит действие в соответствии с настройками, а в меню наоборот. Но вот для Сезона есть возможность запускать поиск только из меню, лучше это делать в соответствии с настройками.
`		thisURL := URLForXBMC("/show/%d/season/%d/", show.ID, item.Info.Season) + "%s"
		contextLabel := linksLabel
		contextURL := contextPlayURL(thisURL, false)
		if config.Get().ChooseStreamAuto {
			contextLabel = playLabel
		}`

**Comment by elgatito** [comment]
Я придерживаюсь единого формата, где в прямых ссылках используется настройка выбора автоматического воспроизведения, а в контекстных - противоположное. 
Менять для сезона не вижу смысла. Без реализации этого обработчика никто даже не репортил в Quasar.
