### ISSUE TITLE
Удаляется strm файл, при обновлении информации из контекстного меню.

### ISSUE THREAD

**Issue by Nemiroff** [elgatito/elementum#8]
Если в медиатеке выбрать сезон/серию/фильм, далее в контекстном меню выбрать"Сведения о фильме/серии/сезоне" и нажать обновить, удаляется strm файл. Если закомментировать удаление файла в library/refresh.go, то информация обновляется (перевод серии с tmdb и т.п.), файл остается. Удаление файла через меню проходит успешно.

**Comment by elgatito** [comment]
При нажании "Обновить", Kodi делает удаление из медиатеки, с последующим добавлением. Но будет делать добавление или нет - не сообщает.

```
xbmc/VideoLibrary.OnRemove: {"id":4998,"type":"episode"}
```

**Comment by Nemiroff** [comment]
Что изменится в файле strm после обновления? Правильно-ничего. Есть ли тогда смысл его удалять? Возможно стоит удалять инфо про выбранный тип из базы вместо удаления файла ?

**Comment by elgatito** [comment]
Коди говорит что удаляет из библиотеки, соответственно файл удаляется так как он удален со стороны библиотеки. Дополнение никакой информации никуда не добавляет, это всё делает Коди со своей стороны. Всё что делает дополнение - пишет файл на диск.

**Comment by Nemiroff** [comment]
Удаление происходит в методе Update, если закоментировать удаление в этом методе, то при обновлении файл остаётся, при удалении он удаляется, так как метод другой(не смотрел конкретно какой) Проверял сам на Kodi 16.

**Comment by elgatito** [comment]
Если закомментировать удаление по событию `xbmc/VideoLibrary.OnRemove`, то при нажатии "Удалить из медиатеки" в Коди файлы останутся на месте и будут снова добавлены при обновлении.

**Comment by Nemiroff** [comment]
Сейчас точно не помню, но событие бродкастом шлется. Собранные бинарники есть у меня в репозиториях с этим исправлением. Позже гляну снова лог, как там происходит.

**Comment by Nemiroff** [comment]
В файле library/refresh.go методы RefreshShow RefreshMovie RefreshEpisode. В них убрал удаление файла.

**Comment by elgatito** [comment]
Should be fixed in 0.0.46.

**Comment by Nemiroff** [comment]
Файлы не удаляются. Всё работает.
